#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /api/login_check

api_register:
    path: /api/public/register
    controller: App\Controller\ApiController::register
