#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /api/login_check

ride_comparison:
    path: /api/ride/comparison
    controller: App\Controller\RideComparisonAction
    methods: [GET]

password_reset_mail:
    path: /api/password-reset/mail/{email}
    controller: App\Controller\PasswordReset\SendResetPasswordMailAction

password_reset_form:
    path: /api/password-reset
    controller: App\Controller\PasswordReset\ResetPasswordFormAction
