#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /api/login_check

ride_comparison:
    path: /api/ride/comparison
    controller: App\Controller\RideComparisonAction
    methods: [GET]

ride_comparison_v2:
    path: /api/ride/comparison-v2
    controller: App\Controller\RideComparisonV2Action
    methods: [GET]

place_auto_complete:
    path: /api/place/autocomplete/{address}
    controller: App\Controller\PlaceAutoCompleteAction
    methods: [GET]

password_reset_mail:
    path: /api/password-reset/mail/{email}
    controller: App\Controller\PasswordReset\SendResetPasswordMailAction

password_reset_form:
    path: /api/password-reset
    controller: App\Controller\PasswordReset\ResetPasswordFormAction

add_fav:
    path: /api/fav
    controller: App\Controller\AddFavAction
    methods: [POST]
