#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /api/login_check

ride_comparison:
    path: /api/ride/comparison
    controller: App\Controller\RideComparisonAction
    methods: [GET]

password_reset:
    path: /api/password-reset/{email}
    controller: App\Controller\SendResetPasswordMailAction
